services:
  proxy:
    container_name: proxy
    build:
      context: ./proxy
    image: local-proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - server
      - client
  server:
    container_name: server
    build:
      context: ./server
    entrypoint: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python main.py
    image: exercise-server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    image: exercise-client
    command: npm run dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app